[features]
seeds = false
skip-lint = false
[programs.localnet]
mint_nft_skytrade = "3FngfXDHHK2hKhswQKbbtVhi6EHUn1NSgGi2uxEud66E"

[programs.devnet]
mint_nft_skytrade = "3FngfXDHHK2hKhswQKbbtVhi6EHUn1NSgGi2uxEud66E"

[registry]
url = "https://api.apr.dev"


[provider]
cluster = "devnet"
wallet = "/Users/mac/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"


