[features]
seeds = false
skip-lint = false
[programs.localnet]
mint_nft_skytrade = "45dPSsFbkd1nby8ZhoUWUBvQVthExT62AEMXmmq1Qyfs"

[programs.devnet]
mint_nft_skytrade = "45dPSsFbkd1nby8ZhoUWUBvQVthExT62AEMXmmq1Qyfs"


[programs.testnet]
mint_nft_skytrade = "45dPSsFbkd1nby8ZhoUWUBvQVthExT62AEMXmmq1Qyfs"


[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/mac/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"


